version: '3'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=songrequest
      - POSTGRES_USER=songrequest
      - POSTGRES_PASSWORD=test1234!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:
